version: '3'
services:
  jenkins:
    container_name: jenkins-master
    image: jenkins/jenkins:2.391
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-slave:
    container_name: jenkins-slave
    image: jenkins/jnlp-slave:latest
    command: "<secret>"
    environment:
      - JENKINS_URL=http://jenkins:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
